//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaigonRide_FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentalTransaction
    {
        public int TransactionID { get; set; }
        public int UserID { get; set; }
        public int VehicleID { get; set; }
        public int StartStationID { get; set; }
        public Nullable<int> EndStationID { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<decimal> BaseFare { get; set; }
        public Nullable<decimal> AppliedDiscount { get; set; }
        public Nullable<decimal> TotalPaid { get; set; }
        public string PaymentMethod { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
